function handles = CreateGuiElements(handles)
% CREATEGUIELEMENTS create all elements for the user interface used for the
% Editfunction: Baseline
    
    %% create variables
    table = handles.guiprops.Features.edit_curve_table;
    
    % abort if table is empty (means no curves loaded)
    if isempty(table.Data)
        return
    end
    
    panel = handles.guiprops.Panels.results_panel;
    curvename = table.UserData.CurrentCurveName;
    results = handles.curveprops.(curvename).Results.Baseline;
    
    % clear results_panel
    delete(allchild(panel));
    
    %% setup main_vbox for resutls an input parameters for Baseline
    scrolling_panel = uix.ScrollingPanel('Parent', panel);
    main_vbox = uix.VBox('Parent', scrolling_panel,...
        'Padding', 5,...
        'Visible', 'off');
    
    %% input elements
    settings_panel = uix.Panel('Parent', main_vbox,...
        'Padding', 10,...
        'Tag', 'settings_panel',...
        'Title', 'Settings');
    settings_vbox = uix.VBox('Parent', settings_panel,...
        'Spacing', 10,...
        'Tag', 'settings_vbox');
    
    % for correction type
    correction_type_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'correction_type_panel',...
        'Title', 'Correction Type');
    grid1 = uix.Grid('Parent', correction_type_panel,...
        'Tag', 'correction_type__grid1',...
        'Spacing', 5);
    
    offset_label = uicontrol('Parent', grid1,...
        'Style', 'text',...
        'String', 'Offset:',...
        'Tag', 'offset_label');
    offset_radio_btn = uicontrol('Parent', grid1,...
        'Style', 'radiobutton',...
        'Value', 1,...
        'Tag', 'offset_radio_btn');
    offset_tilt_label = uicontrol('Parent', grid1,...
        'Style', 'text',...
        'String', 'Offset + Tilt:',...
        'Tag', 'offset_tilt_label');
    offset_tilt_radio_btn = uicontrol('Parent', grid1,...
        'Style', 'radiobutton',...
        'Value', 0,...
        'Tag', 'offset_tilt_radio_btn');
    
    grid1.Heights = -1;
    grid1.Widths = [-1 30 -1 30];
    
    % for baseline range
    baseline_range_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'baseline_range_panel',...
        'Title', 'Baseline Range');
    grid2 = uix.Grid('Parent', baseline_range_panel,...
        'Tag', 'baseline_range_grid2',...
        'Spacing', 5);
    
    % label for left Border 
    left_border_label = uicontrol('Parent', grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Left Border:');
    left_border_label.Tag = 'left_border_label';

    % edit for left border
    left_border = uicontrol('Parent', grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(1)),...
        'Tag', 'left_border',...
        'Callback', '');

    % label for right border
    right_border_label = uicontrol('Parent', grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Right Border:');
    right_border_label.Tag = 'right_border_label';

    % edit for right border
    right_border = uicontrol('Parent', grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(2)),...
        'Tag', 'right_border',...
        'Callback', '');

    grid2.Heights = -1;
    grid2.Widths = [-1 40 -1 40];
    
    % for units
    units_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'units_panel',...
        'Title', 'Units');
    grid3 = uix.Grid('Parent', units_panel,...
        'Spacing', 5);

    relative_units_label = uicontrol('Parent', grid3,...
        'Style', 'text',...
        'String', 'Relative Units:',...
        'Tag', 'relative_units_label');
    relative_units_radio_btn = uicontrol('Parent', grid3,...
        'Style', 'radiobutton',...
        'Value', 1,...
        'Tag', 'relative_units_radio_btn');
    absolute_units_label = uicontrol('Parent', grid3,...
        'Style', 'text',...
        'String', 'Absolute Units:',...
        'Tag', 'absolute_units_label');
    absolute_units_radio_btn = uicontrol('Parent', grid3,...
        'Style', 'radiobutton',...
        'Value', 0,...
        'Tag', 'absolute_units_radio_btn');
    
    grid3.Heights = -1;
    grid3.Widths = [-1 30 -1 30];
    
    % for curve settings
    curve_settins_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'curve_settins_panel',...
        'Title', 'Curve Settings');
    grid4 = uix.Grid('Parent', curve_settins_panel,...
        'Spacing', 5);
    
    settings_vbox.Heights = [40 45 40 -1];
    %% calculation results
    
    %% settings of main_vbox
    
    % adjust height of main_vbox
    main_vbox.Heights = 300;
%     main_vbox.Heights = [230 80];

    % make layout visible
    main_vbox.Visible = 'on';

    scrolling_panel.Widths = 345;
    scrolling_panel.Heights = 330;
    
    %% update handles-struct

end

