function handles = CreateGuiElements(handles)
% CREATEGUIELEMENTS create all elements for the user interface used for the
% Editfunction: Baseline
    
    %% create variables
    table = handles.guiprops.Features.edit_curve_table;
    
    % abort if table is empty (means no curves loaded)
    if isempty(table.Data)
        return
    end
    
    panel = handles.guiprops.Panels.results_panel;
    curvename = table.UserData.CurrentCurveName;
    results = handles.curveprops.(curvename).Results.Baseline;
    
    % clear results_panel
    delete(allchild(panel));
    
    %% setup main_vbox for input and results parameters for Baseline
    scrolling_panel = uix.ScrollingPanel('Parent', panel);
    main_vbox = uix.VBox('Parent', scrolling_panel,...
        'Padding', 5,...
        'Visible', 'off');
    tab_panel = uix.TabPanel('Parent', main_vbox,...
        'Padding', 5);
    
    %% settings elemmnts: parent
    settings_vbox = uix.VBox('Parent', tab_panel,...
        'Spacing', 5,...
        'Tag', 'baseline_settings_vbox');
    
    settings_panel_1 = uix.Panel('Parent', settings_vbox,...
        'Title', 'Force vs. Distance',...
        'Tag', 'settings_panel_1');
    settings_panel_vbox_1 = uix.VBox('Parent', settings_panel_1,...
        'Spacing', 5,...
        'Padding', 5,...
        'Tag', 'settings_panel_vbox_1');
    
    settings_panel_2 = uix.Panel('Parent', settings_vbox,...
        'Title', 'Force vs. Time',...
        'Tag', 'settings_panel_2');
    settings_panel_vbox_2 = uix.VBox('Parent', settings_panel_2,...
        'Spacing', 5,...
        'Padding', 5,...
        'Tag', 'settings_panel_vbox_2');
    
    %% settings elements: froce vs. distance --> Offset + Tilt
    
    setting_correction_type_panel = uix.Panel('Parent', settings_panel_vbox_1,...
        'Padding', 5,...
        'Tag', 'baseline_correction_type_panel');
    setting_grid1 = uix.Grid('Parent', setting_correction_type_panel,...
        'Tag', 'baseline_correction_type__grid1',...
        'Spacing', 5);

   setting_offset_tilt_label = uicontrol('Parent', setting_grid1,...
        'Style', 'text',...
        'String', 'Offset + Tilt:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_tilt_label');
    setting_offset_tilt_radio_btn = uicontrol('Parent', setting_grid1,...
        'Style', 'radiobutton',...
        'Value', 1,.....
        'Tag', 'baseline_offset_tilt_radio_btn');    

    setting_offset_label = uicontrol('Parent', setting_grid1,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_label');
    setting_offset_radio_btn = uicontrol('Parent', setting_grid1,...
        'Style', 'radiobutton',...
        'Value', 0,...
        'Tag', 'baseline_offset_radio_btn');
    
    setting_grid1.Heights = [15 15];
    setting_grid1.Widths = [-1 -1];
    
    setting_offset_tilt_radio_btn.Callback = {@EditFunctions.Baseline.Callbacks.OffsetTiltValueChangedCallback,...
        setting_offset_radio_btn, 'correction_type'};
    setting_offset_radio_btn.Callback = {@EditFunctions.Baseline.Callbacks.OffsetValueChangedCallback,...
        setting_offset_tilt_radio_btn, 'correction_type'};
    
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_label = setting_offset_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_radio_btn = setting_offset_radio_btn;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_label = setting_offset_tilt_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_radio_btn = setting_offset_tilt_radio_btn;
    
    %% settings elements: force vs. distance --> baseline range
    
    setting_baseline_range_panel = uix.Panel('Parent', settings_panel_vbox_1,...
        'Padding', 5,...
        'Tag', 'baseline_range_panel');
    setting_grid2 = uix.Grid('Parent', setting_baseline_range_panel,...
        'Tag', 'baseline_range_grid2',...
        'Spacing', 5);
    
    
    setting_left_border_label = uicontrol('Parent', setting_grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Left Border:',...
        'Tag', 'baseline_left_border_label');
    setting_left_border = uicontrol('Parent', setting_grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(1)),...
        'Value', results.selection_borders(1),...
        'Tag', 'baseline_left_border');
    setting_right_border_label = uicontrol('Parent', setting_grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Right Border:',...
        'Tag', 'baseline_right_border_label');
    setting_right_border = uicontrol('Parent', setting_grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(2)),...
        'Value', results.selection_borders(2),...
        'Tag', 'baseline_right_border');

    setting_grid2.Heights = [15 20];
    setting_grid2.Widths = [-1 -1];
    
    setting_left_border.Callback = {@EditFunctions.Baseline.Callbacks.LeftBorderValueChangedCallback,...
        'selection_borders'};
    setting_right_border.Callback = {@EditFunctions.Baseline.Callbacks.RightBorderValueChangedCallback,...
        'selection_borders'};

    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border_label = setting_left_border_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border = setting_left_border;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border_label = setting_right_border_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border = setting_right_border;

    %% settings elements: force vs. distance --> curve settings
    parts_idx = handles.curveprops.(curvename).Results.Baseline.curve_parts_index;
    segments_idx = handles.curveprops.(curvename).Results.Baseline.curve_segments_index;
    parts = handles.guiprops.Features.curve_parts_popup;
    segments = handles.guiprops.Features.curve_segments_popup;
    
    curve_settins_panel = uix.Panel('Parent', settings_panel_vbox_1,...
        'Padding', 5,...
        'Tag', 'curve_settins_panel');
    setting_grid3 = uix.Grid('Parent', curve_settins_panel,...
        'Spacing', 5);
    
    setting_parts_label = uicontrol('Parent', setting_grid3,...
        'Style', 'text',...
        'String', 'Parts:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_parts_label');
    setting_segments_label = uicontrol('Parent', setting_grid3,...
        'Style', 'text',...
        'String', 'Segments:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_segments_label');
    setting_parts_dropdown = uicontrol('Parent', setting_grid3,...
        'Style', 'popupmenu',...
        'String', parts.String,...
        'Value', parts_idx,...
        'Tag', 'baseline_parts_dropdown',...
        'Callback', {@EditFunctions.Baseline.Callbacks.CurvePartsDropdownCallback,...
        'curve_parts_index'});
    setting_segments_dropdown = uicontrol('Parent', setting_grid3,...
        'Style', 'popupmenu',...
        'String', segments.String,...
        'Value', segments_idx,...
        'Tag', 'baseline_segments_dropdown',...
        'Callback', {@EditFunctions.Baseline.Callbacks.CurveSegmentsDropdownCallback,...
        'curve_parts_index',...
        'curve_segments_index'});
    
    setting_grid3.Heights = [20 20];
    setting_grid3. Widths = [-1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_label = setting_parts_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_label = setting_segments_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_dropdown = setting_parts_dropdown;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_dropdown = setting_segments_dropdown;
    
    %% settings elements: force vs. distance --> select range button
    setting_grid4 = uix.Grid('Parent', settings_panel_vbox_1,...
        'Spacing', 5);
    
    settings_empty = uix.Empty('Parent', setting_grid4,...
        'Tag', 'setting_empty');
    settings_select_range_btn = uicontrol('Parent', setting_grid4,...
        'Style', 'togglebutton',...
        'String', 'Select Range',...
        'Tag', 'setting_select_range_btn',...
        'Callback', @EditFunctions.Baseline.Callbacks.SelectRangeToggle1Callback);
    
    setting_grid4.Heights = 25;
    setting_grid4.Widths = [-1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.settings_empty = settings_empty;
    handles.procedure.Baseline.function_properties.gui_elements.settings_select_range_btn = settings_select_range_btn;
    
    %% settings elements: force vs. time --> offset + tilt
    
    setting_correction_type_panel_2 = uix.Panel('Parent', settings_panel_vbox_2,...
        'Padding', 5,...
        'Tag', 'baseline_correction_type_panel_2');
    setting_grid1_2 = uix.Grid('Parent', setting_correction_type_panel_2,...
        'Tag', 'baseline_correction_type__grid1_2',...
        'Spacing', 5);
    
   setting_offset_tilt_label_2 = uicontrol('Parent', setting_grid1_2,...
        'Style', 'text',...
        'String', 'Offset + Tilt:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_tilt_label_2');
    setting_offset_tilt_radio_btn_2 = uicontrol('Parent', setting_grid1_2,...
        'Style', 'radiobutton',...
        'Value', 1,.....
        'Tag', 'baseline_offset_tilt_radio_btn_2');
    
    setting_offset_label_2 = uicontrol('Parent', setting_grid1_2,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_label');
    setting_offset_radio_btn_2 = uicontrol('Parent', setting_grid1_2,...
        'Style', 'radiobutton',...
        'Value', 0,...
        'Tag', 'baseline_offset_radio_btn_2');
    
    setting_grid1_2.Heights = [15 15];
    setting_grid1_2.Widths = [-1 -1];
    
    setting_offset_tilt_radio_btn_2.Callback = {@EditFunctions.Baseline.Callbacks.OffsetTiltValueChangedCallback,...
        setting_offset_radio_btn_2, 'correction_type_2'};
    setting_offset_radio_btn_2.Callback = {@EditFunctions.Baseline.Callbacks.OffsetValueChangedCallback,...
        setting_offset_tilt_radio_btn_2, 'correction_type_2'};
    
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_label_2 = setting_offset_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_radio_btn_2 = setting_offset_radio_btn_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_label_2 = setting_offset_tilt_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_radio_btn_2 = setting_offset_tilt_radio_btn_2;

    
    %% settings elements: force vs. time --> baseline range
    
    setting_baseline_range_panel_2 = uix.Panel('Parent', settings_panel_vbox_2,...
        'Padding', 5,...
        'Tag', 'baseline_range_panel_2');
    setting_grid2_2 = uix.Grid('Parent', setting_baseline_range_panel_2,...
        'Tag', 'baseline_range_grid2_2',...
        'Spacing', 5);
    
    
    setting_left_border_label_2 = uicontrol('Parent', setting_grid2_2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Left Border:',...
        'Tag', 'baseline_left_border_label_2');
    setting_left_border_2 = uicontrol('Parent', setting_grid2_2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(1)),...
        'Value', results.selection_borders(1),...
        'Tag', 'baseline_left_border_2');
    setting_right_border_label_2 = uicontrol('Parent', setting_grid2_2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Right Border:',...
        'Tag', 'baseline_right_border_label_2');
    setting_right_border_2 = uicontrol('Parent', setting_grid2_2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(2)),...
        'Value', results.selection_borders(2),...
        'Tag', 'baseline_right_border_2');

    setting_grid2_2.Heights = [15 20];
    setting_grid2_2.Widths = [-1 -1];
    
    setting_left_border_2.Callback = {@EditFunctions.Baseline.Callbacks.LeftBorderValueChangedCallback,...
        'selection_borders_2'};
    setting_right_border_2.Callback = {@EditFunctions.Baseline.Callbacks.RightBorderValueChangedCallback,...
        'selection_borders_2'};
    
    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border_label_2 = setting_left_border_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border_2 = setting_left_border_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border_label_2 = setting_right_border_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border_2 = setting_right_border_2;
    
    %% settings elements: force vs. time --> curve settings
    parts_idx = handles.curveprops.(curvename).Results.Baseline.curve_parts_index_2;
    segments_idx = handles.curveprops.(curvename).Results.Baseline.curve_segments_index_2;
    parts = handles.guiprops.Features.curve_parts_popup;
    segments = handles.guiprops.Features.curve_segments_popup;
    
    curve_settins_panel_2 = uix.Panel('Parent', settings_panel_vbox_2,...
        'Padding', 5,...
        'Tag', 'curve_settins_panel');
    setting_grid3_2 = uix.Grid('Parent', curve_settins_panel_2,...
        'Spacing', 5);
    
    setting_parts_label_2 = uicontrol('Parent', setting_grid3_2,...
        'Style', 'text',...
        'String', 'Parts:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_parts_label_2');
    setting_segments_label_2 = uicontrol('Parent', setting_grid3_2,...
        'Style', 'text',...
        'String', 'Segments:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_segments_label_2');
    setting_parts_dropdown_2 = uicontrol('Parent', setting_grid3_2,...
        'Style', 'popupmenu',...
        'String', parts.String,...
        'Value', parts_idx,...
        'Tag', 'baseline_parts_dropdown_2',...
        'Callback', {@EditFunctions.Baseline.Callbacks.CurvePartsDropdownCallback,...
        'curve_parts_index_2'});
    setting_segments_dropdown_2 = uicontrol('Parent', setting_grid3_2,...
        'Style', 'popupmenu',...
        'String', segments.String,...
        'Value', segments_idx,...
        'Tag', 'baseline_segments_dropdown_2',...
        'Callback', {@EditFunctions.Baseline.Callbacks.CurveSegmentsDropdownCallback,...
        'curve_parts_index_2',...
        'curve_segments_index_2'});
    
    setting_grid3_2.Heights = [20 20];
    setting_grid3_2. Widths = [-1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_label_2 = setting_parts_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_label_2 = setting_segments_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_dropdown_2 = setting_parts_dropdown_2;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_dropdown_2 = setting_segments_dropdown_2;
    
    %% settings elements: force vs. time --> select range button
    setting_grid4_2 = uix.Grid('Parent', settings_panel_vbox_2,...
        'Spacing', 5);
    
    settings_empty_2 = uix.Empty('Parent', setting_grid4_2,...
        'Tag', 'setting_empty_2');
    settings_select_range_btn_2 = uicontrol('Parent', setting_grid4_2,...
        'Style', 'togglebutton',...
        'String', 'Select Range',...
        'Tag', 'setting_select_range_btn_2',...
        'Callback', @EditFunctions.Baseline.Callbacks.SelectRangeToggle2Callback);
    
    setting_grid4_2.Heights = 25;
    setting_grid4_2.Widths = [-1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.settings_empty_2 = settings_empty_2;
    handles.procedure.Baseline.function_properties.gui_elements.settings_select_range_btn_2 = settings_select_range_btn_2;

    
    %% calculation results elements: parent
    results_vbox = uix.VBox('Parent', tab_panel,...
        'Spacing', 5,...
        'Tag', 'baseline_results_vbox');
    results_panel_1 = uix.Panel('Parent', results_vbox,...
        'Title', 'Force vs. Distance',...
        'Padding', 5,...
        'Tag', 'results_panel_1');
    
    results_panel_2 = uix.Panel('Parent', results_vbox,...
        'Title', 'Force vs. Time',...
        'Padding', 5,...
        'Tag', 'results_panel_2');
    results_grid_2 = uix.Grid('Parent', results_panel_2,...
        'Spacing', 5);
    
    %% calculation results elements: force vs. distance --> offset + tilt
    
    offset_value = handles.curveprops.(curvename).Results.Baseline.offset;
    tilt_value = handles.curveprops.(curvename).Results.Baseline.slope;
    
    results_grid_1 = uix.Grid('Parent', results_panel_1,...
        'Spacing', 5);
    
    results_offset_label = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_offset_label');
    results_tilt_label = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', 'Tilt:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_tilt_label');
    
    results_offset_value = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', num2str(offset_value),...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_offset_value');
    results_tilt_value = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', num2str(tilt_value),...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_tilt_value');
    
    results_offset_unit = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', 'N',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_offset_unit');
    results_tilt_unit = uicontrol('Parent', results_grid_1,...
        'Style', 'text',...
        'String', 'N/m',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_tilt_unit');
    
    results_grid_1.Heights = [-1 -1];
    results_grid_1.Widths = [-1 -1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_label = results_offset_label;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_value = results_offset_value;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_unit = results_offset_unit;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_label = results_tilt_label;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_value = results_tilt_value;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_unit = results_tilt_unit;

    %% calculation results elements: force vs. time --> offset + tilt
    
    offset_value = handles.curveprops.(curvename).Results.Baseline.offset_2;
    tilt_value = handles.curveprops.(curvename).Results.Baseline.slope_2;
    
    results_offset_label_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_offset_label_2');
    results_tilt_label_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', 'Tilt:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_tilt_label_2');
    
    results_offset_value_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', num2str(offset_value),...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_offset_value_2');
    results_tilt_value_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', num2str(tilt_value),...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_tilt_value_2');
    
    results_offset_unit_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', 'N',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_offset_unit_2');
    results_tilt_unit_2 = uicontrol('Parent', results_grid_2,...
        'Style', 'text',...
        'String', 'N/s',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_tilt_unit_2');
    
    results_grid_2.Heights = [-1 -1];
    results_grid_2.Widths = [-1 -1 -1];
    
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_label_2 = results_offset_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_value_2 = results_offset_value_2;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_unit_2 = results_offset_unit_2;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_label_2 = results_tilt_label_2;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_value_2 = results_tilt_value_2;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_unit_2 = results_tilt_unit_2;
    
    %% Tabs for tab_panel
    tab_panel.TabTitles = {'Settings', 'Results'};
    
    %% positional settigs for panels
    
    settings_vbox.Heights = [250 250];
    settings_panel_vbox_1.Heights = [-1 -1 -1 25];
    settings_panel_vbox_2.Heights = [-1 -1 -1 25];
    results_vbox.Heights = [100 100];
    main_vbox.Heights = 550;
    scrolling_panel.Widths = -1;
    scrolling_panel.Heights = 550;

    % make layout visible
    main_vbox.Visible = 'on';
    
end

