function handles = CreateGuiElements(handles)
% CREATEGUIELEMENTS create all elements for the user interface used for the
% Editfunction: Baseline
    
    %% create variables
    table = handles.guiprops.Features.edit_curve_table;
    
    % abort if table is empty (means no curves loaded)
    if isempty(table.Data)
        return
    end
    
    panel = handles.guiprops.Panels.results_panel;
    curvename = table.UserData.CurrentCurveName;
    results = handles.curveprops.(curvename).Results.Baseline;
    
    % clear results_panel
    delete(allchild(panel));
    
    %% setup main_vbox for resutls an input parameters for Baseline
    scrolling_panel = uix.ScrollingPanel('Parent', panel);
    main_vbox = uix.VBox('Parent', scrolling_panel,...
        'Padding', 5,...
        'Visible', 'off');
    tab_panel = uix.TabPanel('Parent', main_vbox,...
        'Padding', 5);
    
    %% input elements
    settings_vbox = uix.VBox('Parent', tab_panel,...
        'Spacing', 5,...
        'Tag', 'baseline_settings_vbox');
    
    % for correction type
    setting_correction_type_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'baseline_correction_type_panel',...
        'Title', 'Correction Type');
    setting_grid1 = uix.Grid('Parent', setting_correction_type_panel,...
        'Tag', 'baseline_correction_type__grid1',...
        'Spacing', 5);
    
    setting_offset_label = uicontrol('Parent', setting_grid1,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_label');
    setting_offset_radio_btn = uicontrol('Parent', setting_grid1,...
        'Style', 'radiobutton',...
        'Value', 1,...
        'Tag', 'baseline_offset_radio_btn',...
        'Callback', @EditFunctions.Baseline.Callbacks.OffsetValueChangedCallback);
    setting_offset_tilt_label = uicontrol('Parent', setting_grid1,...
        'Style', 'text',...
        'String', 'Offset + Tilt:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_offset_tilt_label');
    setting_offset_tilt_radio_btn = uicontrol('Parent', setting_grid1,...
        'Style', 'radiobutton',...
        'Value', 0,.....
        'Tag', 'baseline_offset_tilt_radio_btn',...
        'Callback', @EditFunctions.Baseline.Callbacks.OffsetTiltValueChangedCallback);
    
    setting_grid1.Heights = [15 15];
    setting_grid1.Widths = [-1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_label = setting_offset_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_radio_btn = setting_offset_radio_btn;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_label = setting_offset_tilt_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_offset_tilt_radio_btn = setting_offset_tilt_radio_btn;
    
    % for baseline range
    setting_baseline_range_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'baseline_range_panel',...
        'Title', 'Baseline Range');
    setting_grid2 = uix.Grid('Parent', setting_baseline_range_panel,...
        'Tag', 'baseline_range_grid2',...
        'Spacing', 5);
     
    setting_left_border_label = uicontrol('Parent', setting_grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Left Border:',...
        'Tag', 'baseline_left_border_label');
    setting_left_border = uicontrol('Parent', setting_grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(1)),...
        'Value', results.selection_borders(1),...
        'Tag', 'baseline_left_border',...
        'Callback', @EditFunctions.Baseline.Callbacks.LeftBorderValueChangedCallback);
    setting_right_border_label = uicontrol('Parent', setting_grid2,...
        'Style', 'text',...
        'HorizontalAlignment', 'left',...
        'String', 'Right Border:',...
        'Tag', 'baseline_right_border_label');
    setting_right_border = uicontrol('Parent', setting_grid2,...
        'Style', 'edit',...
        'String', num2str(results.selection_borders(2)),...
        'Value', results.selection_borders(2),...
        'Tag', 'baseline_right_border',...
        'Callback', @EditFunctions.Baseline.Callbacks.RightBorderValueChangedCallback);

    setting_grid2.Heights = [15 20];
    setting_grid2.Widths = [-1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border_label = setting_left_border_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_left_border = setting_left_border;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border_label = setting_right_border_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_right_border = setting_right_border;
    
    % for units
    setting_units_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'units_panel',...
        'Title', 'Units');
    setting_grid3 = uix.Grid('Parent', setting_units_panel,...
        'Spacing', 5);

    setting_relative_units_label = uicontrol('Parent', setting_grid3,...
        'Style', 'text',...
        'String', 'Relative Units:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_relative_units_label');
    setting_relative_units_radio_btn = uicontrol('Parent', setting_grid3,...
        'Style', 'radiobutton',...
        'Value', 1,...
        'Tag', 'baseline_relative_units_radio_btn',...
        'Callback', @EditFunctions.Baseline.Callbacks.RelativeUnitsValueChangedCallback);
    setting_absolute_units_label = uicontrol('Parent', setting_grid3,...
        'Style', 'text',...
        'String', 'Absolute Units:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_absolute_units_label');
    setting_absolute_units_radio_btn = uicontrol('Parent', setting_grid3,...
        'Style', 'radiobutton',...
        'Value', 0,...
        'Tag', 'baseline_absolute_units_radio_btn',...
        'Callback', @EditFunctions.Baseline.Callbacks.AbsoluteUnitsValueChangedCallback);
    
    setting_grid3.Heights = [15 15];
    setting_grid3.Widths = [-1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.setting_relative_units_label = setting_relative_units_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_relative_units_radio_btn = setting_relative_units_radio_btn;
    handles.procedure.Baseline.function_properties.gui_elements.setting_absolute_units_label = setting_absolute_units_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_absolute_units_radio_btn = setting_absolute_units_radio_btn;
    
    % for curve settings
    
    parts = handles.guiprops.Features.curve_parts_popup;
    segments = handles.guiprops.Features.curve_segments_popup;
    xchannel = handles.guiprops.Features.curve_xchannel_popup;
    ychannel = handles.guiprops.Features.curve_ychannel_popup;
    
    curve_settins_panel = uix.Panel('Parent', settings_vbox,...
        'Padding', 5,...
        'Tag', 'curve_settins_panel',...
        'Title', 'Curve Settings');
    setting_grid4 = uix.Grid('Parent', curve_settins_panel,...
        'Spacing', 5);
    
    setting_parts_label = uicontrol('Parent', setting_grid4,...
        'Style', 'text',...
        'String', 'Parts:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_parts_label');
    setting_segments_label = uicontrol('Parent', setting_grid4,...
        'Style', 'text',...
        'String', 'Segments:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_segments_label');
    setting_xchannel_label = uicontrol('Parent', setting_grid4,...
        'Style', 'text',...
        'String', 'xchannel:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_xchannel_label');
    setting_ychannel_label = uicontrol('Parent', setting_grid4,...
        'Style', 'text',...
        'String', 'ychannel:',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_ychannel_label');
    setting_parts_dropdown = uicontrol('Parent', setting_grid4,...
        'Style', 'popupmenu',...
        'String', parts.String,...
        'Value', parts.Value,...
        'Tag', 'baseline_parts_dropdown',...
        'Callback', @EditFunctions.Baseline.Callbacks.CurvePartsDropdownCallback);
    setting_segments_dropdown = uicontrol('Parent', setting_grid4,...
        'Style', 'popupmenu',...
        'String', segments.String,...
        'Value', segments.Value,...
        'Tag', 'baseline_segments_dropdown',...
        'Callback', @EditFunctions.Baseline.Callbacks.CurveSegmentsDropdownCallback);
    setting_xchannel_dropdown = uicontrol('Parent', setting_grid4,...
        'Style', 'popupmenu',...
        'String', xchannel.String,...
        'Value', xchannel.Value,...
        'Tag', 'baseline_xchannel_dropdown',...
        'Callback', @EditFunctions.Baseline.Callbacks.CurveXchannelDropdownCallback);
    setting_ychannel_dropdown = uicontrol('Parent', setting_grid4,...
        'Style', 'popupmenu',...
        'String', ychannel.String,...
        'Value', ychannel.Value,...
        'Tag', 'baseline_ychannel_dropdown',...
        'Callback', @EditFunctions.Baseline.Callbacks.CurveYchannelDropdownCallback);
    
    setting_grid4.Heights = [20 20 20 20];
    setting_grid4. Widths = [-1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_label = setting_parts_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_label = setting_segments_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_xchannel_label = setting_xchannel_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_ychannel_label = setting_ychannel_label;
    handles.procedure.Baseline.function_properties.gui_elements.setting_parts_dropdown = setting_parts_dropdown;
    handles.procedure.Baseline.function_properties.gui_elements.setting_segments_dropdown = setting_segments_dropdown;
    handles.procedure.Baseline.function_properties.gui_elements.setting_xchannel_dropdown = setting_xchannel_dropdown;
    handles.procedure.Baseline.function_properties.gui_elements.setting_ychannel_dropdown = setting_ychannel_dropdown;
    
    %% calculation results
    results_panel = uix.Panel('Parent', tab_panel,...
        'Padding', 5,...
        'Tag', 'baseline_results_panel',...
        'Title', 'Calculated Results');
    results_vbox = uix.VBox('Parent', results_panel,...
        'Spacing', 5,...
        'Tag', 'baseline_results_vbox');
    
    % for offset
    results_grid1 = uix.Grid('Parent', results_vbox,...
        'Spacing', 5);
    
    results_offset_label = uicontrol('Parent', results_grid1,...
        'Style', 'text',...
        'String', 'Offset:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_offset_label');
    results_offset_value = uicontrol('Parent', results_grid1,...
        'Style', 'text',...
        'String', '...',...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_offset_value');
    results_offset_unit = uicontrol('Parent', results_grid1,...
        'Style', 'text',...
        'String', '...',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_offset_unit');
    
    results_grid1.Heights = 20;
    results_grid1.Widths = [-1 -1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.results_offset_label = results_offset_label;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_value = results_offset_value;
    handles.procedure.Baseline.function_properties.gui_elements.results_offset_unit = results_offset_unit;
    
    % for slope
    results_grid2 = uix.Grid('Parent', results_vbox,...
        'Spacing', 5);
    
    results_tilt_label = uicontrol('Parent', results_grid2,...
        'Style', 'text',...
        'String', 'Tilt:',...
        'HorizontalAlignment', 'right',...
        'Tag', 'baseline_results_tilt_label');
    results_tilt_value = uicontrol('Parent', results_grid2,...
        'Style', 'text',...
        'String', '...',...
        'HorizontalAlignment', 'center',...
        'Tag', 'baseline_results_tilt_value');
    results_tilt_unit = uicontrol('Parent', results_grid2,...
        'Style', 'text',...
        'String', '...',...
        'HorizontalAlignment', 'left',...
        'Tag', 'baseline_results_tilt_unit');
    
    results_grid1.Heights = 20;
    results_grid1.Widths = [-1 -1 -1];

    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_label = results_tilt_label;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_value = results_tilt_value;
    handles.procedure.Baseline.function_properties.gui_elements.results_tilt_unit = results_tilt_unit;
    
    %% Tabs for tab_panel
    tab_panel.TabTitles = {'Settings', 'Results'};
    
    %% positional settigs for panels
    
    settings_vbox.Heights = [65 70 65 -1];
    results_vbox.Heights = [20 20];
    main_vbox.Heights = 370;
    scrolling_panel.Widths = 320;
    scrolling_panel.Heights = 380;

    % make layout visible
    main_vbox.Visible = 'on';
        
end

