function handles = SetPropertyListener(handles)
% SETPROPERTYLISTENER set the property listener for the functionality
% of the baseline-editfunction

    %% create variables
    table = handles.guiprops.Features.edit_curve_table;
    
    % abort if tabel is empty (means no curves loaded)
    if isempty(table.Data) || isempty(table.UserData)
        return
    end
    
    curvenames = fieldnames(handles.curveprops.DynamicProps);
    current_curvename = table.UserData.CurrentCurveName;
    current_baseline = handles.curveprops.(current_curvename).Results.Baseline;
    
    %% create listener
    for i = 1:length(curvenames)
        curvename = curvenames{i};
        baseline = handles.curveprops.(curvename).Results.Baseline;
        baseline.property_listener = PropListener();

        % Baseline Range: update border-edit-controls
        baseline.property_listener.addListener(baseline, 'selection_borders', 'PostSet',...
            @EditFunctions.Baseline.Callbacks.UpdateBorderElementsCallback);

        % Curve Settings: update dropdown menus
        baseline.property_listener.addListener(baseline, 'curve_parts_index', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.BLUpdateDropdownMenuCallback,...
            'setting_parts_dropdown',...
            'setting_segments_dropdown',...
            'curve_parts_index'});
        baseline.property_listener.addListener(baseline, 'curve_parts_index_2', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.BLUpdateDropdownMenuCallback,...
            'setting_parts_dropdown_2',...
            'setting_segments_dropdown_2',...
            'curve_parts_index_2'});
        
        % Results: update offset and tilt values
        baseline.property_listener.addListener(baseline, 'offset', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.UpdateCalculatedOffsetValueCallback,...
            'results_offset_value',...
            'offset'});
        baseline.property_listener.addListener(baseline, 'slope', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.UpdateCalculatedTiltValueCallback,...
            'results_tilt_value',...
            'slope'});
        baseline.property_listener.addListener(baseline, 'offset_2', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.UpdateCalculatedOffsetValueCallback,...
            'results_offset_value_2',...
            'offset_2'});
        baseline.property_listener.addListener(baseline, 'slope_2', 'PostSet',...
            {@EditFunctions.Baseline.Callbacks.UpdateCalculatedTiltValueCallback,...
            'results_tilt_value_2',...
            'slope_2'});
        
        %% update handles-struct
        handles.curveprops.(curvename).Results.Baseline = baseline;
    end
    

end

