fig = figure();
panel = uix.Panel('Parent', fig);
box = uix.Grid('Parent', panel);
btn1 = uicontrol('Parent', box,...
    'Style', 'pushbutton',...
    'String', 'test1');
btn2 = uicontrol('Parent', box,...
    'Style', 'pushbutton',...
    'String', 'test2');
btn3 = uicontrol('Parent', box,...
    'Style', 'pushbutton',...
    'String', 'test3');
label = TextLabel('Parent', box,...
    'String', 'TestLabel',...
    'HorizontalAlignment', 'center',...
    'VerticalAlignment', 'center');
box.Widths = [-1 -1];
box.Heights = [-1 -1];